language: php
php:
  - 7.2
  - 7.3
matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  # Add the oauth token to prevent GitHub timeouts.
  # - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
before_script:
  - composer --version
  - composer remove drupal/migrate_tools
  - composer global require drush/drush
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
install:
  - composer update
script:
  - drush si -y
  #- php scripts/quickstart install
