language: php
php:
  - 7.2
  - 7.3
matrix:
  fast_finish: true

before_install:
  - phpenv config-rm xdebug.ini
  # Add the oauth token to prevent GitHub timeouts.
  # - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
before_script:
  - composer --version
  - if [[ -n "$DRUPAL_CORE" ]]; then composer require drupal/core:$DRUPAL_CORE --update-with-all-dependencies; fi
  - composer require drush/drush
  - rm composer.lock
install:
  - composer update
script:
  - ./vendor/drush/drush/drush si -y
  #- php scripts/quickstart install
